name = "JavisNB"
uuid = "92afb270-2599-44f6-96a1-44c6efb1daf1"
authors = ["Jacob Zelko <jacobszelko@gmail.com>", "Giovanni Puccetti <g.puccetti92@gmail.com>"]
version = "0.1.0"

[deps]
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Javis = "78b212ba-a7f9-42d4-b726-60726080707e"

[compat]
julia = "1.6"
Interact = "0.10"
Javis = "0.7.2"
